[versions]
kotlin = { version = "1.2.51", group = "org.jetbrains.kotlin" }
jackson = { version = "2.9.6", group = "com.fasterxml.jackson.core" }
jacksonData = { version = "2.9.6", group = "com.fasterxml.jackson.datatype" }
jacksonModule = { version = "2.9.6", group = "com.fasterxml.jackson.module" }
spring = { version = "5.1.2.RELEASE", group = "org.springframework" }
springBoot = { version = "2.1.0.RELEASE", group = "org.springframework.boot" }

[libraries]
common = [
    'com.google.guava:guava:26.0-jre',
    'org.hibernate.validator:hibernate-validator:6.0.12.Final',
    'org.glassfish:javax.el:3.0.1-b08'
]

kotlin = [
    "org.jetbrains.kotlin:kotlin-stdlib",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
    "org.jetbrains.kotlin:kotlin-reflect"
]

logging = [
    "org.slf4j:slf4j-api:1.7.25",
    'org.apache.logging.log4j:log4j-core:2.11.1',
    'org.apache.logging.log4j:log4j-slf4j18-impl:2.11.1'
]

spring = [
    'org.springframework:spring-context',
    'org.springframework:spring-webflux',
    'org.springframework:spring-tx',
    'org.springframework:spring-jdbc',
    'org.springframework:spring-context-support',
    'io.projectreactor.netty:reactor-netty:0.8.2.RELEASE',
    'org.springframework.boot:spring-boot',
    'org.springframework.boot:spring-boot-autoconfigure',
    'org.springframework.boot:spring-boot-starter',
    'org.springframework.boot:spring-boot-starter-aop',
    'org.springframework.boot:spring-boot-actuator',
    'org.springframework.boot:spring-boot-starter-actuator',
    'io.micrometer:micrometer-registry-graphite:latest.release',
    'io.micrometer:micrometer-registry-prometheus:latest.release',
    'io.lettuce:lettuce-core:5.0.5.RELEASE',
    'org.yaml:snakeyaml:1.23'
]

httpClient = [
    'io.projectreactor.ipc:reactor-netty:0.7.8.RELEASE',
    'io.mikael:urlbuilder:2.0.9'
]

database = [
    "mysql:mysql-connector-java:8.0.11",
    "com.zaxxer:HikariCP:3.3.1",
    "org.jooq:jooq:3.11.3",
    "org.jooq:jooq-meta:3.11.3",
    "org.flywaydb:flyway-core:5.2.1"
]

commonsLang = [
        "org.apache.commons:commons-lang3:3.7"
]

freemarker = [
    'org.freemarker:freemarker:2.3.28'
]

springAnnotation = [
    "org.springframework.boot:spring-boot-configuration-processor"
]

jackson = [
        "com.fasterxml.jackson.core:jackson-annotations",
        "com.fasterxml.jackson.core:jackson-databind",
        "com.fasterxml.jackson.datatype:jackson-datatype-jsr310",
        "com.fasterxml.jackson.module:jackson-module-kotlin"
]

jwt = [
    'io.jsonwebtoken:jjwt:0.6.0'
]

jooqCodeGen = [
    "org.jooq:jooq:3.11.3",
    "org.jooq:jooq-meta:3.11.3",
    "org.jooq:jooq-codegen:3.11.3",
    "mysql:mysql-connector-java:8.0.11",
    'com.sun.xml.bind:jaxb-impl:2.2.11',
    'com.sun.xml.bind:jaxb-core:2.2.11',
    'javax.activation:activation:1.1.1'
]

validations = [
    'javax.persistence:javax.persistence-api:2.2',
    'javax.validation:validation-api:2.0.1.Final'
]

oauth = [
    'com.github.scribejava:scribejava-apis:6.3.0',
    'com.github.scribejava:scribejava-core:6.3.0',
    'io.mikael:urlbuilder:2.0.9'
]

testingLibraries = [
    "org.mockito:mockito-core:1.10.19",
    "com.jayway.jsonpath:json-path:2.2.0",
    "cglib:cglib:3.2.5",
    "org.objenesis:objenesis:2.2",
    "org.ow2.asm:asm:5.0.4",
    "de.sven-jacobs:loremipsum:1.0",
    "org.jetbrains.kotlin:kotlin-test-junit5:1.2.51",
    'com.github.tomakehurst:wiremock:2.18.0'
    'org.hamcrest:hamcrest-library:1.3',
    'org.assertj:assertj-core:3.9.1'
]