version: '3'
services:
  postgres:
    image: postgres
    expose: 
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
 # Jaeger
  # jaeger-all-in-one:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "16686:16686"
  #     - "14268"
  #     - "14250"

  # # Zipkin
  # zipkin-all-in-one:
  #   image: openzipkin/zipkin:latest
  #   ports:
  #     - "9411:9411"
  
  # gadget:
  #   image: 5eabf949f84b
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
  #     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
  #   depends_on:
  #     - otel-collector
  #   links:
  #     - otel-collector

  # Collector
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib-dev:latest
  #   command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
  #   volumes:
  #     - ./dev-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   expose: 
  #     - 4317
  #   ports:
  #     - "1888:1888"   # pprof extension
  #     - "8888:8888"   # Prometheus metrics exposed by the collector
  #     - "8889:8889"   # Prometheus exporter metrics
  #     - "13133:13133" # health_check extension
  #     - "4317:4317"   # OTLP gRPC receiver
  #     - "55670:55679" # zpages extension
  #   depends_on:
  #     - jaeger-all-in-one
  #     - zipkin-all-in-one

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./dev-config/prometheus.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
