[package]
name = "gadget"
version = "0.1.0"
authors = ["Ethan Hall <ethan@ehdev.io>"]
edition = "2018"


[features]
default = []
postgres = ["diesel", "r2d2"]

[dependencies]
serde = { version = "1.0", features = ["derive"]}
diesel = { version = "1.4", features = ["postgres", "chrono", "r2d2"], optional = true  }
clap = { version = "2.33" }
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
flexi_logger = { version = "0.14", features = ["specfile", "ziplogs", "colors"] }
log = "0.4"
r2d2 = { version = "0.8", optional = true }
rand = "0.7"
lazy_static = "1.4"
prometheus = "0.7"
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-service = "1.0.4"
actix-files = "0.2.1"
serde_json = "1.0.44"
futures-util = "0.3.1"
futures = "0.3.1"
mime_guess = "2.0.1"
url = "2.1.0"