version: '3'
services:
  postgres:
    image: postgres
    expose: 
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  jaeger:
    image: jaegertracing/all-in-one:latest
    expose: 
      - 6831/udp
      - 14250
    ports:
      - "6831:6831/udp"
      - '14250:14250'
      - "16686:16686"