//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "global_usage"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub usage_id: i32,
    pub global_redirects_id: i32,
    pub clicks: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    UsageId,
    GlobalRedirectsId,
    Clicks,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    UsageId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    GlobalRedirects,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::UsageId => ColumnType::Integer.def(),
            Self::GlobalRedirectsId => ColumnType::Integer.def(),
            Self::Clicks => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::GlobalRedirects => Entity::belongs_to(super::global_redirects::Entity)
                .from(Column::GlobalRedirectsId)
                .to(super::global_redirects::Column::GlobalRedirectsId)
                .into(),
        }
    }
}

impl Related<super::global_redirects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlobalRedirects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
