name: Publish Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure version
        run: |
          docker run --rm -v $(pwd):/target ghcr.io/ethankhall/crom/cli:latest write-version custom ${{ inputs.version }}
      - name: Build local image - with cache update
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx build \
            --output=type=registry \
            --file Dockerfile \
            --cache-to type=registry,ref=ghcr.io/ethankhall/gadget-cache,mode=max \
            --cache-from type=registry,ref=ghcr.io/ethankhall/gadget-cache \
            --tag ghcr.io/ethankhall/gadget:$(git rev-parse --short HEAD) \
            --tag ghcr.io/ethankhall/gadget:${{ inputs.version }} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
      - name: Build local image
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          docker buildx build \
            --file Dockerfile \
            --cache-from type=registry,ref=ghcr.io/ethankhall/gadget-cache \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
