on:
  push:
    branches:
    - main

name: Release

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        id: version
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get next-release)
          gh release create $VERSION --generate-notes --target $(git rev-parse HEAD) --draft
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  publish:
    uses: ./.github/workflows/create-artifacts.yml
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}

  remove-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: undraft release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release edit ${{ needs.create-release.outputs.version }} --draft=false

  tag-latest:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - remove-draft
    steps:
      - name: Update latest tag
        run: |
          set -e
          docker login ghcr.io --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/ethankhall/gadget:${{ needs.create-release.outputs.version }}
          docker tag ghcr.io/ethankhall/gadget:${{ needs.create-release.outputs.version }} ghcr.io/ethankhall/gadget:latest
          docker push ghcr.io/ethankhall/gadget:latest

  check:
    name: Run Validates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: validate artifact
        run: |
          docker buildx build \
            --cache-from type=registry,ref=ghcr.io/ethankhall/gadget-cache \
            --cache-from type=registry,ref=ghcr.io/ethankhall/gadget-cache:validate \
            --cache-to type=registry,ref=ghcr.io/ethankhall/gadget-cache:validate,mode=max \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --target check .
