name: Rust

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    container:
      image: rustlang/rust:nightly

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
