name: PR Test

on:
  pull_request:
    branches:
    - master

jobs:
  build-rust:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build gadget
      run: docker build -t gadget-server rust-applications

  build-webapp:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build webapp
      run: docker build -t gadget-local-ui gadget-local-ui
