name: Publish Image

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: login to registry
      run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gadget
    - name: push to registry
      run: |
        docker tag slack-pagerduty docker.pkg.github.com/ethankhall/gadget-rust/gadget:$(git rev-parse --short HEAD)
        docker tag slack-pagerduty docker.pkg.github.com/ethankhall/gadget-rust/gadget:latest
        docker push docker.pkg.github.com/ethankhall/gadget-rust/gadget:$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/ethankhall/gadget-rust/gadget:latest

