name: Publish Image

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: login to registry
      run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        set -e
        docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest tag next-release --local --github
        VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get latest | sed 's/v//g')
        docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest write-version latest
        docker build . --file Dockerfile --tag gadget
        docker run --rm gadget /app/bin/gadget --help
    - name: push to registry
      run: |
        set -e
        VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get latest | sed 's/v//g')
        docker tag gadget docker.pkg.github.com/ethankhall/gadget-rust/gadget:$(git rev-parse --short HEAD)
        docker tag gadget docker.pkg.github.com/ethankhall/gadget-rust/gadget:latest
        docker tag gadget docker.pkg.github.com/ethankhall/gadget-rust/gadget:$VERSION
        docker push docker.pkg.github.com/ethankhall/gadget-rust/gadget:$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/ethankhall/gadget-rust/gadget:latest
        docker push docker.pkg.github.com/ethankhall/gadget-rust/gadget:$VERSION

